// asciidoctor -T ../asciidoctor-backends/slim slides.adoc
= Writing Documentation: Use Cases, Workflows and Obstacles
Sarah White
include::attributes.ad[]

== !

documentation

. Material that provides official information or evidence or that serves as a record.
. The written specification and instructions accompanying a computer program or hardware.

== !

@carbonfray

== !

The horror

== !

open source is 

== !

a symbiotic relationship with your community and reality

== !

bad impressions and bad habits

== !

documentation workflow

the highs and the lows

== !

Asciidoctor

== !

it all started with a README...


== !

then a magazine article


== !

which got turned into the first document

== ! 

and it went live on a webpage


== !

chop and sort


== !

release outlook 0.1.2


== !

release announcement and changelog

== !

READMEs galore (Divergence! Ack!)


== !

Meanwhile, the organization is growing, the coders are coding

== !

rinse and repeat

== !

audiences

== !

duplication and maintenance

== !

requirements + contributions + culture

== !

collaboration

== !

UX hasn't even entered this conversation

== !

next...

== !

time to tell your documentation stories

